// Copyright 2015 Eryx <evorui аt gmаil dοt cοm>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.5.0
// source: kvspec.proto

package kvspec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Public_Query_FullMethodName       = "/lynkdb.kvspec.v2.Public/Query"
	Public_Commit_FullMethodName      = "/lynkdb.kvspec.v2.Public/Commit"
	Public_BatchCommit_FullMethodName = "/lynkdb.kvspec.v2.Public/BatchCommit"
	Public_SysCmd_FullMethodName      = "/lynkdb.kvspec.v2.Public/SysCmd"
)

// PublicClient is the client API for Public service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicClient interface {
	Query(ctx context.Context, in *ObjectReader, opts ...grpc.CallOption) (*ObjectResult, error)
	Commit(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error)
	BatchCommit(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResult, error)
	SysCmd(ctx context.Context, in *SysCmdRequest, opts ...grpc.CallOption) (*ObjectResult, error)
}

type publicClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicClient(cc grpc.ClientConnInterface) PublicClient {
	return &publicClient{cc}
}

func (c *publicClient) Query(ctx context.Context, in *ObjectReader, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Public_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) Commit(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Public_Commit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) BatchCommit(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResult, error) {
	out := new(BatchResult)
	err := c.cc.Invoke(ctx, Public_BatchCommit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) SysCmd(ctx context.Context, in *SysCmdRequest, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Public_SysCmd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServer is the server API for Public service.
// All implementations must embed UnimplementedPublicServer
// for forward compatibility
type PublicServer interface {
	Query(context.Context, *ObjectReader) (*ObjectResult, error)
	Commit(context.Context, *ObjectWriter) (*ObjectResult, error)
	BatchCommit(context.Context, *BatchRequest) (*BatchResult, error)
	SysCmd(context.Context, *SysCmdRequest) (*ObjectResult, error)
	mustEmbedUnimplementedPublicServer()
}

// UnimplementedPublicServer must be embedded to have forward compatible implementations.
type UnimplementedPublicServer struct {
}

func (UnimplementedPublicServer) Query(context.Context, *ObjectReader) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedPublicServer) Commit(context.Context, *ObjectWriter) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPublicServer) BatchCommit(context.Context, *BatchRequest) (*BatchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCommit not implemented")
}
func (UnimplementedPublicServer) SysCmd(context.Context, *SysCmdRequest) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysCmd not implemented")
}
func (UnimplementedPublicServer) mustEmbedUnimplementedPublicServer() {}

// UnsafePublicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicServer will
// result in compilation errors.
type UnsafePublicServer interface {
	mustEmbedUnimplementedPublicServer()
}

func RegisterPublicServer(s grpc.ServiceRegistrar, srv PublicServer) {
	s.RegisterService(&Public_ServiceDesc, srv)
}

func _Public_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectReader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Public_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).Query(ctx, req.(*ObjectReader))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectWriter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Public_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).Commit(ctx, req.(*ObjectWriter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_BatchCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).BatchCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Public_BatchCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).BatchCommit(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_SysCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).SysCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Public_SysCmd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).SysCmd(ctx, req.(*SysCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Public_ServiceDesc is the grpc.ServiceDesc for Public service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Public_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynkdb.kvspec.v2.Public",
	HandlerType: (*PublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Public_Query_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Public_Commit_Handler,
		},
		{
			MethodName: "BatchCommit",
			Handler:    _Public_BatchCommit_Handler,
		},
		{
			MethodName: "SysCmd",
			Handler:    _Public_SysCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvspec.proto",
}

const (
	Internal_Prepare_FullMethodName = "/lynkdb.kvspec.v2.Internal/Prepare"
	Internal_Accept_FullMethodName  = "/lynkdb.kvspec.v2.Internal/Accept"
	Internal_LogSync_FullMethodName = "/lynkdb.kvspec.v2.Internal/LogSync"
	Internal_SysCmd_FullMethodName  = "/lynkdb.kvspec.v2.Internal/SysCmd"
)

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalClient interface {
	Prepare(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error)
	Accept(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error)
	LogSync(ctx context.Context, in *LogSyncRequest, opts ...grpc.CallOption) (*LogSyncReply, error)
	SysCmd(ctx context.Context, in *SysCmdRequest, opts ...grpc.CallOption) (*ObjectResult, error)
}

type internalClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalClient(cc grpc.ClientConnInterface) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) Prepare(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Internal_Prepare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) Accept(ctx context.Context, in *ObjectWriter, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Internal_Accept_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) LogSync(ctx context.Context, in *LogSyncRequest, opts ...grpc.CallOption) (*LogSyncReply, error) {
	out := new(LogSyncReply)
	err := c.cc.Invoke(ctx, Internal_LogSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) SysCmd(ctx context.Context, in *SysCmdRequest, opts ...grpc.CallOption) (*ObjectResult, error) {
	out := new(ObjectResult)
	err := c.cc.Invoke(ctx, Internal_SysCmd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
// All implementations must embed UnimplementedInternalServer
// for forward compatibility
type InternalServer interface {
	Prepare(context.Context, *ObjectWriter) (*ObjectResult, error)
	Accept(context.Context, *ObjectWriter) (*ObjectResult, error)
	LogSync(context.Context, *LogSyncRequest) (*LogSyncReply, error)
	SysCmd(context.Context, *SysCmdRequest) (*ObjectResult, error)
	mustEmbedUnimplementedInternalServer()
}

// UnimplementedInternalServer must be embedded to have forward compatible implementations.
type UnimplementedInternalServer struct {
}

func (UnimplementedInternalServer) Prepare(context.Context, *ObjectWriter) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedInternalServer) Accept(context.Context, *ObjectWriter) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedInternalServer) LogSync(context.Context, *LogSyncRequest) (*LogSyncReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogSync not implemented")
}
func (UnimplementedInternalServer) SysCmd(context.Context, *SysCmdRequest) (*ObjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysCmd not implemented")
}
func (UnimplementedInternalServer) mustEmbedUnimplementedInternalServer() {}

// UnsafeInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServer will
// result in compilation errors.
type UnsafeInternalServer interface {
	mustEmbedUnimplementedInternalServer()
}

func RegisterInternalServer(s grpc.ServiceRegistrar, srv InternalServer) {
	s.RegisterService(&Internal_ServiceDesc, srv)
}

func _Internal_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectWriter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Prepare(ctx, req.(*ObjectWriter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectWriter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Accept(ctx, req.(*ObjectWriter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_LogSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).LogSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_LogSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).LogSync(ctx, req.(*LogSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_SysCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).SysCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_SysCmd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).SysCmd(ctx, req.(*SysCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Internal_ServiceDesc is the grpc.ServiceDesc for Internal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynkdb.kvspec.v2.Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Internal_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Internal_Accept_Handler,
		},
		{
			MethodName: "LogSync",
			Handler:    _Internal_LogSync_Handler,
		},
		{
			MethodName: "SysCmd",
			Handler:    _Internal_SysCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvspec.proto",
}
